- name: Install php repo.
  yum:
     name: "{{ php_repo_url}}"
     state: present
  environment: "{{ proxy_env }}"

- name: "Configure remi repository"
  shell: "yum-config-manager --enable remi-php{{ php_ver }}"
  environment: "{{ proxy_env }}"


- name: install php
  yum:
    name: php72
  environment: "{{ proxy_env }}"

- name: Install php modules
  yum:
     name: "{{ packages }}"
  environment: "{{ proxy_env }}"
  vars:
    packages:  
    - php-fpm
    - php-common
    - php-mysql
    - php-gmp
    - php-curl
    - php-intl
    - php-mbstring
    - php-xmlrpc
    - php-gd
    - php-bcmath
    - php-imap
    - php-xml
    - php-cli
    - php-zip
    - php-pecl-redis
    - php-ldap
    - php-pecl-oci8
    - php-pecl-ssh2
    - php-oci8

- name: Download oracle-instantclient
  get_url:
    url: https://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient21/x86_64/getPackage/oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm
    dest: /tmp/oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm
  environment: "{{ proxy_env }}"
    
- name: Install oracle-instantclient from a local file
  yum:
    name: /tmp/oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm
    state: present


