- name: restart smb 
  systemd:
    state: restarted
    daemon_reload: yes
    name: smb
  
- name: restart nmb 
  systemd:
    state: restarted
    daemon_reload: yes
    name: nmb

- name: restart sshd 
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd